// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mozeyfuwcbnsjnhokijv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vemV5ZnV3Y2Juc2puaG9raWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjMyODYsImV4cCI6MjA2NDUzOTI4Nn0.rtKUdWFG7cQtpRzf3aRmuDqLeiatFRUtNqoSXPEk5Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);